server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pin-Sheng-Huang/microservicecloud-config.git
          default-label: main
          #git@github.com:Pin-Sheng-Huang/microservicecloud-config.git #GitHub上面的git仓库名字
#          search-paths: sub/son/  # 通过模式匹配来检索子目录sub下的配置文件
#網站訪問：http://config-3344.com:3344/application/test/main
#2.http://config-3344.com:3344/application-test.yml